from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ...enums import *
from ...traits import *

from ...core.Geometry_autogen import Geometry


class BoxGeometry(Geometry):
    """BoxGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Tue Oct 18 2016 14:57:27 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/BoxGeometry 
    """
    
    _view_name = Unicode('BoxGeometryView').tag(sync=True)
    _model_name = Unicode('BoxGeometryModel').tag(sync=True)

    width = CFloat(10).tag(sync=True)
    height = CFloat(10).tag(sync=True)
    depth = CFloat(10).tag(sync=True)
    widthSegments = CInt(1).tag(sync=True)
    heightSegments = CInt(1).tag(sync=True)
    depthSegments = CInt(1).tag(sync=True)

