from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ...core.Geometry_autogen import Geometry


class BoxGeometry(Geometry):
    """BoxGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:59:18 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/BoxGeometry 
    """

    def __init__(self, width=10, height=10, depth=10, widthSegments=1, heightSegments=1, depthSegments=1, **kwargs):
        kwargs['width'] = width
        kwargs['height'] = height
        kwargs['depth'] = depth
        kwargs['widthSegments'] = widthSegments
        kwargs['heightSegments'] = heightSegments
        kwargs['depthSegments'] = depthSegments
        super(Geometry, self).__init__(**kwargs)

    _view_name = Unicode('BoxGeometryView').tag(sync=True)
    _model_name = Unicode('BoxGeometryModel').tag(sync=True)

    width = CFloat(10).tag(sync=True)
    height = CFloat(10).tag(sync=True)
    depth = CFloat(10).tag(sync=True)
    widthSegments = CInt(1).tag(sync=True)
    heightSegments = CInt(1).tag(sync=True)
    depthSegments = CInt(1).tag(sync=True)

