from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ...enums import *
from ...traits import *

from ...core.BufferGeometry_autogen import BufferGeometry


class CircleBufferGeometry(BufferGeometry):
    """CircleBufferGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Tue Oct 18 2016 14:57:27 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/CircleBufferGeometry 
    """
    
    _view_name = Unicode('CircleBufferGeometryView').tag(sync=True)
    _model_name = Unicode('CircleBufferGeometryModel').tag(sync=True)

    radius = CFloat(50).tag(sync=True)
    segments = CInt(8).tag(sync=True)
    thetaStart = CFloat(0).tag(sync=True)
    thetaLength = CFloat(6.283185307179586).tag(sync=True)

