from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ...enums import *
from ...traits import *

from ...core.BufferGeometry_autogen import BufferGeometry

from ...math.Vector2_autogen import Vector2

class LatheBufferGeometry(BufferGeometry):
    """LatheBufferGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/LatheBufferGeometry 
    """
    
    _view_name = Unicode('LatheBufferGeometryView').tag(sync=True)
    _model_name = Unicode('LatheBufferGeometryModel').tag(sync=True)

    points = Tuple().tag(sync=True, **widget_serialization)
    segments = CInt(12).tag(sync=True)
    phiStart = CFloat(0).tag(sync=True)
    phiLength = CFloat(6.283185307179586).tag(sync=True)

