from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ...core.BufferGeometry_autogen import BufferGeometry


class LatheBufferGeometry(BufferGeometry):
    """LatheBufferGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/LatheBufferGeometry 
    """
    
    _view_name = Unicode('LatheBufferGeometryView').tag(sync=True)
    _model_name = Unicode('LatheBufferGeometryModel').tag(sync=True)

    points = List(trait=List()).tag(sync=True)
    segments = CInt(12).tag(sync=True)
    phiStart = CFloat(0).tag(sync=True)
    phiLength = CFloat(6.283185307179586).tag(sync=True)

