from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ...core.Geometry_autogen import Geometry


class LatheGeometry(Geometry):
    """LatheGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:47:51 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/LatheGeometry 
    """

    def __init__(self, points=[], segments=12, phiStart=0, phiLength=6.283185307179586, **kwargs):
        kwargs['points'] = points
        kwargs['segments'] = segments
        kwargs['phiStart'] = phiStart
        kwargs['phiLength'] = phiLength
        super(Geometry, self).__init__(**kwargs)

    _view_name = Unicode('LatheGeometryView').tag(sync=True)
    _model_name = Unicode('LatheGeometryModel').tag(sync=True)

    points = List(trait=List()).tag(sync=True)
    segments = CInt(12).tag(sync=True)
    phiStart = CFloat(0).tag(sync=True)
    phiLength = CFloat(6.283185307179586).tag(sync=True)

