from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ...core.Geometry_autogen import Geometry


class PlaneGeometry(Geometry):
    """PlaneGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:59:19 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/PlaneGeometry 
    """

    def __init__(self, width=10, height=10, widthSegments=1, heightSegments=1, **kwargs):
        kwargs['width'] = width
        kwargs['height'] = height
        kwargs['widthSegments'] = widthSegments
        kwargs['heightSegments'] = heightSegments
        super(Geometry, self).__init__(**kwargs)

    _view_name = Unicode('PlaneGeometryView').tag(sync=True)
    _model_name = Unicode('PlaneGeometryModel').tag(sync=True)

    width = CFloat(10).tag(sync=True)
    height = CFloat(10).tag(sync=True)
    widthSegments = CInt(1).tag(sync=True)
    heightSegments = CInt(1).tag(sync=True)

