from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ...enums import *
from ...traits import *

from ...core.Geometry_autogen import Geometry


class PolyhedronGeometry(Geometry):
    """PolyhedronGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Tue Oct 18 2016 14:57:27 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/PolyhedronGeometry 
    """
    
    _view_name = Unicode('PolyhedronGeometryView').tag(sync=True)
    _model_name = Unicode('PolyhedronGeometryModel').tag(sync=True)

    vertices = List().tag(sync=True)
    faces = List().tag(sync=True)
    radius = CFloat(1).tag(sync=True)
    detail = CFloat(0).tag(sync=True)

