from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ...core.Geometry_autogen import Geometry


class PolyhedronGeometry(Geometry):
    """PolyhedronGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 17:17:08 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/PolyhedronGeometry 
    """

    def __init__(self, vertices=[], faces=[], radius=1, detail=0, **kwargs):
        kwargs['vertices'] = vertices
        kwargs['faces'] = faces
        kwargs['radius'] = radius
        kwargs['detail'] = detail
        super(Geometry, self).__init__(**kwargs)

    _view_name = Unicode('PolyhedronGeometryView').tag(sync=True)
    _model_name = Unicode('PolyhedronGeometryModel').tag(sync=True)

    vertices = List().tag(sync=True)
    indices = List().tag(sync=True)
    radius = CFloat(1).tag(sync=True)
    detail = CFloat(0).tag(sync=True)
    faces = List().tag(sync=True)

