from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ...core.BufferGeometry import BufferGeometry


class SphereBufferGeometry(BufferGeometry):
    """SphereBufferGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:47:51 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/SphereBufferGeometry 
    """

    def __init__(self, radius=50, widthSegments=8, heightSegments=6, phiStart=0, phiLength=6.283185307179586, thetaStart=0, thetaLength=3.141592653589793, **kwargs):
        kwargs['radius'] = radius
        kwargs['widthSegments'] = widthSegments
        kwargs['heightSegments'] = heightSegments
        kwargs['phiStart'] = phiStart
        kwargs['phiLength'] = phiLength
        kwargs['thetaStart'] = thetaStart
        kwargs['thetaLength'] = thetaLength
        super(BufferGeometry, self).__init__(**kwargs)

    _view_name = Unicode('SphereBufferGeometryView').tag(sync=True)
    _model_name = Unicode('SphereBufferGeometryModel').tag(sync=True)

    radius = CInt(50).tag(sync=True)
    widthSegments = CInt(8).tag(sync=True)
    heightSegments = CInt(6).tag(sync=True)
    phiStart = CFloat(0).tag(sync=True)
    phiLength = CFloat(6.283185307179586).tag(sync=True)
    thetaStart = CFloat(0).tag(sync=True)
    thetaLength = CFloat(3.141592653589793).tag(sync=True)

