from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ...core.BufferGeometry_autogen import BufferGeometry


class TorusKnotBufferGeometry(BufferGeometry):
    """TorusKnotBufferGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 17:17:08 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/TorusKnotBufferGeometry 
    """

    def __init__(self, radius=100, tube=40, tubularSegments=64, radialSegments=8, p=2, q=3, **kwargs):
        kwargs['radius'] = radius
        kwargs['tube'] = tube
        kwargs['tubularSegments'] = tubularSegments
        kwargs['radialSegments'] = radialSegments
        kwargs['p'] = p
        kwargs['q'] = q
        super(BufferGeometry, self).__init__(**kwargs)

    _view_name = Unicode('TorusKnotBufferGeometryView').tag(sync=True)
    _model_name = Unicode('TorusKnotBufferGeometryModel').tag(sync=True)

    radius = CFloat(100).tag(sync=True)
    tube = CFloat(40).tag(sync=True)
    tubularSegments = CInt(64).tag(sync=True)
    radialSegments = CInt(8).tag(sync=True)
    p = CInt(2).tag(sync=True)
    q = CInt(3).tag(sync=True)

