from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ...core.Geometry_autogen import Geometry

from ..core.Curve_autogen import Curve

class TubeGeometry(Geometry):
    """TubeGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:59:19 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/TubeGeometry 
    """

    def __init__(self, path=None, segments=64, radius=1, radiusSegments=8, close=False, **kwargs):
        kwargs['path'] = path
        kwargs['segments'] = segments
        kwargs['radius'] = radius
        kwargs['radiusSegments'] = radiusSegments
        kwargs['close'] = close
        super(Geometry, self).__init__(**kwargs)

    _view_name = Unicode('TubeGeometryView').tag(sync=True)
    _model_name = Unicode('TubeGeometryModel').tag(sync=True)

    path = Instance(Curve, allow_none=True).tag(sync=True, **widget_serialization)
    segments = CInt(64).tag(sync=True)
    radius = CFloat(1).tag(sync=True)
    radiusSegments = CInt(8).tag(sync=True)
    close = Bool(False).tag(sync=True)

