from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ...core.Geometry_autogen import Geometry

from ..core.Curve_autogen import Curve

class TubeGeometry(Geometry):
    """TubeGeometry
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Geometries/TubeGeometry 
    """
    
    _view_name = Unicode('TubeGeometryView').tag(sync=True)
    _model_name = Unicode('TubeGeometryModel').tag(sync=True)

    path = Instance(Curve, allow_none=True).tag(sync=True, **widget_serialization)
    segments = CInt(64).tag(sync=True)
    radius = CFloat(1).tag(sync=True)
    radiusSegments = CInt(8).tag(sync=True)
    close = Bool(False).tag(sync=True)

