# install and test

VENV_ACTIVATE=.venv/bin/activate

.venv/bin/activate:
	@echo "### Creating Python virtual environment ###"
	python3.9 -m venv .venv


.venv/.done: .venv/bin/activate
	@echo "### Installing Python dependencies ###"
	. $(VENV_ACTIVATE) && \
	pip install -e . && \
	pip install jupyterlab
	@touch $@

test: .venv/.done
	. $(VENV_ACTIVATE) && \
	pip install nbval scikit-image ipywebrtc matplotlib && \
	python -m pytest -vv -l --nbval-lax --current-env .

js/.done: .venv/.done
	cd js && \
	npm run autogen && \
	npm run build:all && \
	jupyter labextension link .
	@touch  $@

run: js/.done
	jupyter lab

# remove all autogenerated files
clean:
	rm -rf .venv
	find js/src -name "*autogen*" -exec rm {} +
	-rm -- pythreejs/**/__init__.py
	-rm -- js/src/**/index.js
	rm -rf pythreejs/static/
	-rm js/package-lock.json
	-rm js/yarn.lock
	rm -rf pythreejs/labextension
