from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .Light_autogen import Light


class AmbientLight(Light):
    """AmbientLight
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Lights/AmbientLight 
    """
    
    _view_name = Unicode('AmbientLightView').tag(sync=True)
    _model_name = Unicode('AmbientLightModel').tag(sync=True)


