from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .Light_autogen import Light

from ..core.Object3D import Object3D

class DirectionalLight(Light):
    """DirectionalLight
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Lights/DirectionalLight 
    """
    
    _view_name = Unicode('DirectionalLightView').tag(sync=True)
    _model_name = Unicode('DirectionalLightModel').tag(sync=True)

    target = Instance(Object3D, allow_none=True).tag(sync=True, **widget_serialization)
    castsShadow = Bool(False).tag(sync=True)

