from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .Light_autogen import Light


class HemisphereLight(Light):
    """HemisphereLight
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Lights/HemisphereLight 
    """
    
    _view_name = Unicode('HemisphereLightView').tag(sync=True)
    _model_name = Unicode('HemisphereLightModel').tag(sync=True)

    groundColor = Unicode("#000000").tag(sync=True)

