from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from ..core.Object3D import Object3D


class Light(Object3D):
    """Light
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Lights/Light 
    """
    
    _view_name = Unicode('LightView').tag(sync=True)
    _model_name = Unicode('LightModel').tag(sync=True)

    color = Unicode("#ffffff").tag(sync=True)
    intensity = CFloat(1).tag(sync=True)

