from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .Light_autogen import Light

from ..core.Object3D import Object3D

class SpotLight(Light):
    """SpotLight
    
    Autogenerated by generate-wrappers.js 
    Date: Tue Oct 18 2016 14:57:27 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Lights/SpotLight 
    """
    
    _view_name = Unicode('SpotLightView').tag(sync=True)
    _model_name = Unicode('SpotLightModel').tag(sync=True)

    target = Instance(Object3D, allow_none=True).tag(sync=True, **widget_serialization)
    distance = CFloat(0).tag(sync=True)
    angle = CFloat(1.0471975511965976).tag(sync=True)
    penumbra = CFloat(0).tag(sync=True)
    decay = CFloat(1).tag(sync=True)

