from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ...enums import *
from ...traits import *

from ..._base.Three import ThreeWidget


class ClosedSplineCurve3(ThreeWidget):
    """ClosedSplineCurve3
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Extras.Curves/ClosedSplineCurve3 
    """
    
    _view_name = Unicode('ClosedSplineCurve3View').tag(sync=True)
    _model_name = Unicode('ClosedSplineCurve3Model').tag(sync=True)


