from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from ..core.Object3D import Object3D

from .Fog_autogen import Fog
from ..materials.Material_autogen import Material

class Scene(Object3D):
    """Scene
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:47:51 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Scenes/Scene 
    """

    def __init__(self, **kwargs):
        super(Object3D, self).__init__(**kwargs)

    _view_name = Unicode('SceneView').tag(sync=True)
    _model_name = Unicode('SceneModel').tag(sync=True)

    fog = Instance(Fog, allow_none=True).tag(sync=True, **widget_serialization)
    overrideMaterial = Instance(Material, allow_none=True).tag(sync=True, **widget_serialization)
    autoUpdate = Bool(True).tag(sync=True)

