#!/usr/bin/env bash
set -eux

pushd js
jlpm --ignore-optional
popd

python setup.py sdist
python -m pip install -v dist/pythreejs*.tar.gz --no-deps --ignore-installed

# validate
jupyter nbextension list
jupyter labextension list
