#!/usr/bin/env bash
set -eux

export PIP_DISABLE_PIP_VERSION_CHECK=1
export PYTHONUNBUFFERED=1
export PYTHONIOENCODING=utf-8

pushd js
jlpm --ignore-optional
popd

# install and validate python environment
python setup.py sdist

pushd dist
python -m pip install -v pythreejs*.tar.gz --no-deps
popd

python -m pip check || echo "uh oh"

# ensure labextension is linked
jupyter labextension develop . --overwrite

# build docs
pushd docs
make html
popd

# validate extensions
jupyter nbextension list
jupyter labextension list
