from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class WebGLRenderer(ThreeWidget):
    """WebGLRenderer
    
    Autogenerated by generate-wrappers.js 
    Date: Mon Oct 17 2016 17:36:18 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Renderers/WebGLRenderer 
    """
    
    _view_name = Unicode('WebGLRendererView').tag(sync=True)
    _model_name = Unicode('WebGLRendererModel').tag(sync=True)


