def install_nbextension(**kwargs):
    """Install the appropriate html and javascript into the IPython nbextension.

    Keyword arguments will be passed on to the IPython install_nbextension function.
    """
    import os.path
    from IPython.html import nbextensions
    #kwargs.setdefault('symlink', True)
    pkgdir = os.path.dirname(__file__)
    nbextensions.install_nbextension([os.path.join(pkgdir, 'nbextensions', 'pythreejs')], **kwargs)

from .pythreejs import (
    Texture, 
    ImageTexture, 
    DataTexture, 
    Color, 
    Object3d, 
    ScaledObject, 
    Controls, 
    OrbitControls, 
    Picker, 
    Geometry, 
    PlainGeometry, 
    SphereGeometry, 
    CylinderGeometry, 
    BoxGeometry, 
    CircleGeometry, 
    LatheGeometry, 
    TubeGeometry, 
    IcosahedronGeometry, 
    OctahedronGeometry, 
    PlaneGeometry, 
    TetrahedronGeometry, 
    TorusGeometry, 
    TorusKnotGeometry, 
    PolyhedronGeometry, 
    RingGeometry, 
    SurfaceGeometry, 
    FaceGeometry, 
    ParametricGeometry, 
    Material, 
    BasicMaterial, 
    LambertMaterial, 
    PhongMaterial, 
    DepthMaterial, 
    LineBasicMaterial, 
    LineDashedMaterial, 
    NormalMaterial, 
    ParticleSystemMaterial, 
    ShaderMaterial, 
    SpriteMaterial, 
    Sprite, 
    TextTexture, 
    Mesh, 
    Line, 
    PlotMesh, 
    Camera, 
    PerspectiveCamera, 
    OrthographicCamera, 
    Scene, 
    Effect, 
    AnaglyphEffect, 
    Renderer, 
    Light, 
    AmbientLight, 
    IntensityLight, 
    HemisphereLight, 
    DirectionalLight, 
    PointLight, 
    SpotLight, 
    SurfaceGrid,
    lights)


# don't include install_nbextension when we import *
__all__ = ["Texture", 
           "ImageTexture", 
           "DataTexture", 
           "Color", 
           "Object3d", 
           "ScaledObject", 
           "Controls", 
           "OrbitControls", 
           "Picker", 
           "Geometry", 
           "PlainGeometry", 
           "SphereGeometry", 
           "CylinderGeometry", 
           "BoxGeometry", 
           "CircleGeometry", 
           "LatheGeometry", 
           "TubeGeometry", 
           "IcosahedronGeometry", 
           "OctahedronGeometry", 
           "PlaneGeometry", 
           "TetrahedronGeometry", 
           "TorusGeometry", 
           "TorusKnotGeometry", 
           "PolyhedronGeometry", 
           "RingGeometry", 
           "SurfaceGeometry", 
           "FaceGeometry", 
           "ParametricGeometry", 
           "Material", 
           "BasicMaterial", 
           "LambertMaterial", 
           "PhongMaterial", 
           "DepthMaterial", 
           "LineBasicMaterial", 
           "LineDashedMaterial", 
           "NormalMaterial", 
           "ParticleSystemMaterial", 
           "ShaderMaterial", 
           "SpriteMaterial", 
           "Sprite", 
           "TextTexture", 
           "Mesh", 
           "Line", 
           "PlotMesh", 
           "Camera", 
           "PerspectiveCamera", 
           "OrthographicCamera", 
           "Scene", 
           "Effect", 
           "AnaglyphEffect", 
           "Renderer", 
           "Light", 
           "AmbientLight", 
           "IntensityLight", 
           "HemisphereLight", 
           "DirectionalLight", 
           "PointLight", 
           "SpotLight", 
           "SurfaceGrid",
           "lights",
       ]
