from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from .enums import *
from .traits import *

from ._base.Three import ThreeWidget


class Three(ThreeWidget):
    """Three
    
    Autogenerated by generate-wrappers.js 
    Date: Sun Oct 16 2016 14:44:54 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Three 
    """
    
    _view_name = Unicode('ThreeView').tag(sync=True)
    _model_name = Unicode('ThreeModel').tag(sync=True)


