from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .Material_autogen import Material


class MeshDepthMaterial(Material):
    """MeshDepthMaterial
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:59:18 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Materials/MeshDepthMaterial 
    """

    _view_name = Unicode('MeshDepthMaterialView').tag(sync=True)
    _model_name = Unicode('MeshDepthMaterialModel').tag(sync=True)

    morphTargets = Bool(False).tag(sync=True)
    wireframe = Bool(False).tag(sync=True)
    wireframeLinewidth = CFloat(1).tag(sync=True)

