from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .Material_autogen import Material


class MeshNormalMaterial(Material):
    """MeshNormalMaterial
    
    Autogenerated by generate-wrappers.js 
    Date: Tue Oct 18 2016 14:57:27 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Materials/MeshNormalMaterial 
    """
    
    _view_name = Unicode('MeshNormalMaterialView').tag(sync=True)
    _model_name = Unicode('MeshNormalMaterialModel').tag(sync=True)

    wireframe = Bool(False).tag(sync=True)
    wireframeLinewidth = CFloat(1).tag(sync=True)
    morphTargets = Bool(False).tag(sync=True)

