from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .Material_autogen import Material

from ..textures.Texture_autogen import Texture

class MeshStandardMaterial(Material):
    """MeshStandardMaterial
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:47:51 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Materials/MeshStandardMaterial 
    """

    _view_name = Unicode('MeshStandardMaterialView').tag(sync=True)
    _model_name = Unicode('MeshStandardMaterialModel').tag(sync=True)

    color = Unicode("#ffffff").tag(sync=True)
    roughness = CFloat(0.5).tag(sync=True)
    metalness = CFloat(0.5).tag(sync=True)
    map = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    lightMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    lightMapIntensity = CFloat(1).tag(sync=True)
    aoMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    aoMapIntensity = CFloat(1).tag(sync=True)
    emissive = Unicode("#000000").tag(sync=True)
    emissiveMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    emissiveIntensity = CFloat(1).tag(sync=True)
    bumpMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    bumpScale = CFloat(1).tag(sync=True)
    normalMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    displacementMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    displacementScale = CFloat(1).tag(sync=True)
    displacementBias = CFloat(0).tag(sync=True)
    roughnessMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    metalnessMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    alphaMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    envMap = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    envMapIntensity = CFloat(1).tag(sync=True)
    refractionRatio = CFloat(0.98).tag(sync=True)
    fog = Bool(True).tag(sync=True)
    shading = Enum(Shading, "SmoothShading").tag(sync=True)
    wireframe = Bool(False).tag(sync=True)
    wireframeLinewidth = CFloat(1).tag(sync=True)
    wireframeLinecap = Unicode("round").tag(sync=True)
    wireframeLinejoin = Unicode("round").tag(sync=True)
    vertexColors = Enum(Colors, "NoColors").tag(sync=True)
    skinning = Bool(False).tag(sync=True)
    morphTargets = Bool(False).tag(sync=True)
    morphNormals = Bool(False).tag(sync=True)

