from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .Material_autogen import Material

from ..textures.Texture_autogen import Texture

class PointsMaterial(Material):
    """PointsMaterial
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Materials/PointsMaterial 
    """
    
    _view_name = Unicode('PointsMaterialView').tag(sync=True)
    _model_name = Unicode('PointsMaterialModel').tag(sync=True)

    color = Unicode("#ffffff").tag(sync=True)
    map = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    size = CFloat(1).tag(sync=True)
    sizeAttenuation = Bool(True).tag(sync=True)
    vertexColors = Enum(Colors, "NoColors").tag(sync=True)

