from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .Material_autogen import Material


class ShaderMaterial(Material):
    """ShaderMaterial
    
    Autogenerated by generate-wrappers.js 
    Date: Tue Oct 18 2016 14:57:27 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Materials/ShaderMaterial 
    """
    
    _view_name = Unicode('ShaderMaterialView').tag(sync=True)
    _model_name = Unicode('ShaderMaterialModel').tag(sync=True)

    uniforms = Dict().tag(sync=True)
    vertexShader = Unicode("").tag(sync=True)
    fragmentShader = Unicode("").tag(sync=True)

