from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .Material_autogen import Material

from ..textures.Texture_autogen import Texture

class SpriteMaterial(Material):
    """SpriteMaterial
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:47:51 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Materials/SpriteMaterial 
    """

    _view_name = Unicode('SpriteMaterialView').tag(sync=True)
    _model_name = Unicode('SpriteMaterialModel').tag(sync=True)

    color = Unicode("#ffffff").tag(sync=True)
    map = Instance(Texture, allow_none=True).tag(sync=True, **widget_serialization)
    rotation = CFloat(0).tag(sync=True)

