from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class BufferAttribute(ThreeWidget):
    """BufferAttribute
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Core/BufferAttribute 
    """
    
    _view_name = Unicode('BufferAttributeView').tag(sync=True)
    _model_name = Unicode('BufferAttributeModel').tag(sync=True)

    uuid = Unicode("").tag(sync=True)
    array = List().tag(sync=True)
    itemSize = CInt(1).tag(sync=True)
    count = CInt(0).tag(sync=True)
    needsUpdate = Bool(False).tag(sync=True)
    normalized = Bool(True).tag(sync=True)
    version = CInt(-1).tag(sync=True)

