from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class BufferAttribute(ThreeWidget):
    """BufferAttribute
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 12:40:21 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Core/BufferAttribute 
    """

    def __init__(self, array=[], itemSize=1, normalized=True, **kwargs):
        kwargs['array'] = array
        kwargs['itemSize'] = itemSize
        kwargs['normalized'] = normalized
        super(ThreeWidget, self).__init__(**kwargs)
    _view_name = Unicode('BufferAttributeView').tag(sync=True)
    _model_name = Unicode('BufferAttributeModel').tag(sync=True)

    uuid = Unicode("").tag(sync=True)
    array = List().tag(sync=True)
    itemSize = CInt(1).tag(sync=True)
    count = CInt(0).tag(sync=True)
    needsUpdate = Bool(False).tag(sync=True)
    normalized = Bool(True).tag(sync=True)
    version = CInt(-1).tag(sync=True)

