from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget

from ..math.Ray_autogen import Ray

class Raycaster(ThreeWidget):
    """Raycaster
    
    Autogenerated by generate-wrappers.js 
    Date: Tue Oct 18 2016 14:57:27 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Core/Raycaster 
    """
    
    _view_name = Unicode('RaycasterView').tag(sync=True)
    _model_name = Unicode('RaycasterModel').tag(sync=True)

    origin = Vector3(default=[0,0,0]).tag(sync=True)
    direction = Vector3(default=[0,0,0]).tag(sync=True)
    near = CFloat(0).tag(sync=True)
    far = CFloat(1000000).tag(sync=True)
    ray = Instance(Ray, allow_none=True).tag(sync=True, **widget_serialization)
    linePrecision = CFloat(1).tag(sync=True)

