from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from ..core.Object3D import Object3D

from ..materials.Material_autogen import Material
from ..core.Geometry_autogen import Geometry

class Mesh(Object3D):
    """Mesh
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Objects/Mesh 
    """
    
    _view_name = Unicode('MeshView').tag(sync=True)
    _model_name = Unicode('MeshModel').tag(sync=True)

    material = Instance(Material, allow_none=True).tag(sync=True, **widget_serialization)
    geometry = Instance(Geometry, allow_none=True).tag(sync=True, **widget_serialization)

