from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class Box2(ThreeWidget):
    """Box2
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Box2 
    """
    
    _view_name = Unicode('Box2View').tag(sync=True)
    _model_name = Unicode('Box2Model').tag(sync=True)

    min = Vector2(default=[0,0]).tag(sync=True)
    max = Vector2(default=[0,0]).tag(sync=True)

