from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class Color(ThreeWidget):
    """Color
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Color 
    """
    
    _view_name = Unicode('ColorView').tag(sync=True)
    _model_name = Unicode('ColorModel').tag(sync=True)

    r = CFloat(1).tag(sync=True)
    g = CFloat(1).tag(sync=True)
    b = CFloat(1).tag(sync=True)

