from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class Color(ThreeWidget):
    """Color
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:47:51 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Color 
    """

    def __init__(self, r=1, g=1, b=1, **kwargs):
        kwargs['r'] = r
        kwargs['g'] = g
        kwargs['b'] = b
        super(ThreeWidget, self).__init__(**kwargs)

    _view_name = Unicode('ColorView').tag(sync=True)
    _model_name = Unicode('ColorModel').tag(sync=True)

    r = CFloat(1).tag(sync=True)
    g = CFloat(1).tag(sync=True)
    b = CFloat(1).tag(sync=True)

