from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class Euler(ThreeWidget):
    """Euler
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Euler 
    """
    
    _view_name = Unicode('EulerView').tag(sync=True)
    _model_name = Unicode('EulerModel').tag(sync=True)

    x = CFloat(0).tag(sync=True)
    y = CFloat(0).tag(sync=True)
    z = CFloat(0).tag(sync=True)
    order = Unicode("XYZ").tag(sync=True)

