from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget

from .Plane_autogen import Plane

class Frustum(ThreeWidget):
    """Frustum
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:47:51 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Frustum 
    """

    def __init__(self, p0=None, p1=None, p2=None, p3=None, p4=None, p5=None, **kwargs):
        kwargs['p0'] = p0
        kwargs['p1'] = p1
        kwargs['p2'] = p2
        kwargs['p3'] = p3
        kwargs['p4'] = p4
        kwargs['p5'] = p5
        super(ThreeWidget, self).__init__(**kwargs)

    _view_name = Unicode('FrustumView').tag(sync=True)
    _model_name = Unicode('FrustumModel').tag(sync=True)

    p0 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p1 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p2 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p3 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p4 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p5 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)

