from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget

from .Plane_autogen import Plane

class Frustum(ThreeWidget):
    """Frustum
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 15:52:38 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Frustum 
    """
    
    _view_name = Unicode('FrustumView').tag(sync=True)
    _model_name = Unicode('FrustumModel').tag(sync=True)

    p0 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p1 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p2 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p3 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p4 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)
    p5 = Instance(Plane, allow_none=True).tag(sync=True, **widget_serialization)

