from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class Line3(ThreeWidget):
    """Line3
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:59:18 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Line3 
    """

    def __init__(self, start=[0,0,0], end=[0,0,0], **kwargs):
        kwargs['start'] = start
        kwargs['end'] = end
        super(ThreeWidget, self).__init__(**kwargs)

    _view_name = Unicode('Line3View').tag(sync=True)
    _model_name = Unicode('Line3Model').tag(sync=True)

    start = Vector3(default=[0,0,0]).tag(sync=True)
    end = Vector3(default=[0,0,0]).tag(sync=True)

