from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class Matrix3(ThreeWidget):
    """Matrix3
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Matrix3 
    """
    
    _view_name = Unicode('Matrix3View').tag(sync=True)
    _model_name = Unicode('Matrix3Model').tag(sync=True)

    elements = List().tag(sync=True)

