from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget

from .Vector3_autogen import Vector3

class Spline(ThreeWidget):
    """Spline
    
    Autogenerated by generate-wrappers.js 
    Date: Tue Oct 18 2016 14:57:27 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Spline 
    """
    
    _view_name = Unicode('SplineView').tag(sync=True)
    _model_name = Unicode('SplineModel').tag(sync=True)

    points = Tuple().tag(sync=True, **widget_serialization)

