from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class Vector4(ThreeWidget):
    """Vector4
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Vector4 
    """
    
    _view_name = Unicode('Vector4View').tag(sync=True)
    _model_name = Unicode('Vector4Model').tag(sync=True)

    x = CFloat(0).tag(sync=True)
    y = CFloat(0).tag(sync=True)
    z = CFloat(0).tag(sync=True)
    w = CFloat(0).tag(sync=True)

