from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class Vector3(ThreeWidget):
    """Vector3
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:47:51 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Math/Vector3 
    """

    def __init__(self, x=0, y=0, z=0, **kwargs):
        kwargs['x'] = x
        kwargs['y'] = y
        kwargs['z'] = z
        super(ThreeWidget, self).__init__(**kwargs)

    _view_name = Unicode('Vector3View').tag(sync=True)
    _model_name = Unicode('Vector3Model').tag(sync=True)

    x = CFloat(0).tag(sync=True)
    y = CFloat(0).tag(sync=True)
    z = CFloat(0).tag(sync=True)

