from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


class BufferGeometryLoader(ThreeWidget):
    """BufferGeometryLoader
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Loaders/BufferGeometryLoader 
    """
    
    _view_name = Unicode('BufferGeometryLoaderView').tag(sync=True)
    _model_name = Unicode('BufferGeometryLoaderModel').tag(sync=True)


