from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, Enum, List, Dict, Float, CFloat, Bool

from .Animation import Animation

from ..core.Object3D import Object3D
from ..enums import Shading
from ..base import ThreeView
from ..base import ThreeModel

class AnimationClip(Animation):
    """AnimationClip
    
    Autogenerated by generate-wrappers.js
    Date: Tue Aug 30 2016 08:28:14 GMT-0700 (PDT)
    See http://threejs.org/docs/#Reference/animation/AnimationClip.js
    """
    
    _view_name = Unicode('AnimationClipView').tag(sync=True)
    _model_name = Unicode('AnimationClipModel').tag(sync=True)
    
    name = Unicode("TestAnimation").tag(sync=True)
    noDefault = Instance(Object3D).tag(sync=True, **widget_serialization)
    speed = CInt(20).tag(sync=True)
    duration = CInt(100).tag(sync=True)
    shading = Enum(Shading).tag(sync=True)
