from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from ..core.Object3D import Object3D


class Camera(Object3D):
    """Camera
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Cameras/Camera 
    """
    
    _view_name = Unicode('CameraView').tag(sync=True)
    _model_name = Unicode('CameraModel').tag(sync=True)

    matrixWorldInverse = Matrix4(default=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]).tag(sync=True)
    projectionMatrix = Matrix4(default=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]).tag(sync=True)

