from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from ..core.Object3D import Object3D


class CubeCamera(Object3D):
    """CubeCamera
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Cameras/CubeCamera 
    """
    
    _view_name = Unicode('CubeCameraView').tag(sync=True)
    _model_name = Unicode('CubeCameraModel').tag(sync=True)


