from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from ..core.Object3D import Object3D


class CubeCamera(Object3D):
    """CubeCamera
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 17:17:07 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Cameras/CubeCamera 
    """

    def __init__(self, **kwargs):
        super(Object3D, self).__init__(**kwargs)

    _view_name = Unicode('CubeCameraView').tag(sync=True)
    _model_name = Unicode('CubeCameraModel').tag(sync=True)


