from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .Camera_autogen import Camera


class OrthographicCamera(Camera):
    """OrthographicCamera
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 15:47:51 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Cameras/OrthographicCamera 
    """

    def __init__(self, left=0, right=0, top=0, bottom=0, near=0.1, far=2000, **kwargs):
        kwargs['left'] = left
        kwargs['right'] = right
        kwargs['top'] = top
        kwargs['bottom'] = bottom
        kwargs['near'] = near
        kwargs['far'] = far
        super(Camera, self).__init__(**kwargs)

    _view_name = Unicode('OrthographicCameraView').tag(sync=True)
    _model_name = Unicode('OrthographicCameraModel').tag(sync=True)

    zoom = CFloat(1).tag(sync=True)
    left = CFloat(0).tag(sync=True)
    right = CFloat(0).tag(sync=True)
    top = CFloat(0).tag(sync=True)
    bottom = CFloat(0).tag(sync=True)
    near = CFloat(0.1).tag(sync=True)
    far = CFloat(2000).tag(sync=True)

