from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool, Union, Any

from ..enums import *
from ..traits import *

from .Camera_autogen import Camera


class PerspectiveCamera(Camera):
    """PerspectiveCamera
    
    Autogenerated by generate-wrappers.js 
    Date: Fri Oct 21 2016 17:17:07 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Cameras/PerspectiveCamera 
    """

    def __init__(self, fov=50, aspect=1, near=0.1, far=2000, **kwargs):
        kwargs['fov'] = fov
        kwargs['aspect'] = aspect
        kwargs['near'] = near
        kwargs['far'] = far
        super(Camera, self).__init__(**kwargs)

    _view_name = Unicode('PerspectiveCameraView').tag(sync=True)
    _model_name = Unicode('PerspectiveCameraModel').tag(sync=True)

    fov = CFloat(50).tag(sync=True)
    zoom = CFloat(1).tag(sync=True)
    near = CFloat(0.1).tag(sync=True)
    far = CFloat(2000).tag(sync=True)
    focus = CFloat(10).tag(sync=True)
    aspect = CFloat(1).tag(sync=True)

