from ipywidgets import Widget, DOMWidget, widget_serialization, Color
from traitlets import Unicode, Int, CInt, Instance, This, Enum, Tuple, List, Dict, Float, CFloat, Bool

from ..enums import *
from ..traits import *

from .Camera_autogen import Camera


class PerspectiveCamera(Camera):
    """PerspectiveCamera
    
    Autogenerated by generate-wrappers.js 
    Date: Thu Oct 20 2016 12:05:52 GMT-0700 (PDT) 
    See http://threejs.org/docs/#Reference/Cameras/PerspectiveCamera 
    """
    
    _view_name = Unicode('PerspectiveCameraView').tag(sync=True)
    _model_name = Unicode('PerspectiveCameraModel').tag(sync=True)

    fov = CFloat(50).tag(sync=True)
    zoom = CFloat(1).tag(sync=True)
    near = CFloat(0.1).tag(sync=True)
    far = CFloat(2000).tag(sync=True)
    focus = CFloat(10).tag(sync=True)
    aspect = CFloat(1).tag(sync=True)

